### ISSUE TITLE
maybe use db_region  instead of db_egion

### ISSUE THREAD

**Issue by titimoby** [ovh/public-cloud-examples#28]
https://github.com/ovh/public-cloud-examples/blob/3feb2a9a7ad2b711fb19cdc251ce48ff7cbe3bb1/databases/pgsql/variables.tf#L17

I don't know the impact of this typo but it may be cool to use db_region as the variable name

**Comment by raclepoulpe** [comment]
Thx!
I removed this file because it was part of an obsolete example 👍
