### ISSUE TITLE
feat: ✨ Add rancher demo

### ISSUE THREAD

**Issue by philippart-s** [ovh/public-cloud-examples#46]
Add a demo for Rancher.
For this first demo, leep it simple : 
 - MKS creation (link to the existing demo [Create a MKS cluster with Terraform](https://github.com/ovh/public-cloud-examples/tree/main/containers-orchestration/managed-kubernetes/create-cluster-with-tf)
 - add the steps to add the created MKS in Rancher

**Comment by scraly** [comment]
PR #47 
:-)
